"""empty message

Revision ID: 5a5fe7fcb1ce
Revises: 2cac42590040
Create Date: 2022-08-09 12:50:55.991026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a5fe7fcb1ce'
down_revision = '2cac42590040'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_url', sa.String(length=1000), nullable=True))
    op.drop_constraint('products_name_key', 'products', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('products_name_key', 'products', ['name'])
    op.drop_column('products', 'image_url')
    # ### end Alembic commands ###
