"""empty message

Revision ID: 2cac42590040
Revises: ffdc0a98111c
Create Date: 2022-08-03 12:43:31.510981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cac42590040'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('weapon_type', sa.String(length=50), nullable=False),
    sa.Column('base_damage', sa.Integer(), nullable=True),
    sa.Column('scaling_type', sa.String(length=50), nullable=True),
    sa.Column('can_be_buffed', sa.Boolean(), nullable=True),
    sa.Column('posted', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('reviewBody', sa.String(length=1000), nullable=True),
    sa.Column('posted', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('tagline', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tagline')
    op.drop_column('users', 'image_url')
    op.drop_table('reviews')
    op.drop_table('products')
    # ### end Alembic commands ###
