"""empty message

Revision ID: fb612d7591a2
Revises: ffdc0a98111c
Create Date: 2022-08-02 17:05:05.439448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb612d7591a2'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=True),
    sa.Column('time_sent', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auditor_id', sa.Integer(), nullable=False),
    sa.Column('auditee_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('reviewBody', sa.String(length=1000), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('was_killer', sa.Boolean(), nullable=False),
    sa.Column('disconnected', sa.Boolean(), nullable=False),
    sa.Column('posted', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['auditee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['auditor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('is_helpful', sa.Boolean(), nullable=False),
    sa.Column('is_funny', sa.Boolean(), nullable=False),
    sa.Column('is_salty', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('preferred_role', sa.String(length=8), nullable=False))
    op.add_column('users', sa.Column('favorite_survivor', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('favorite_killer', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('hours', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hours')
    op.drop_column('users', 'favorite_killer')
    op.drop_column('users', 'favorite_survivor')
    op.drop_column('users', 'preferred_role')
    op.drop_table('reactions')
    op.drop_table('reviews')
    op.drop_table('messages')
    # ### end Alembic commands ###
