"""empty message

Revision ID: 4a9761ef3f51
Revises: fb612d7591a2
Create Date: 2022-08-02 18:58:05.484737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a9761ef3f51'
down_revision = 'fb612d7591a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('messages_sender_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['auditor_id'])
    op.drop_constraint('reviews_auditor_id_fkey', 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'users', ['auditor_id'], ['auditor_id'])
    op.add_column('users', sa.Column('auditor_id', sa.Integer(), server_default=sa.text("nextval('auditor_id_seq')"), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auditor_id')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key('reviews_auditor_id_fkey', 'reviews', 'users', ['auditor_id'], ['id'])
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_sender_id_fkey', 'messages', 'users', ['sender_id'], ['id'])
    # ### end Alembic commands ###
